/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Repositorio.mysql;

import java.util.*;
import java.time.*;


import Dominio.Membresías.IMembresiaRepositorio;
// ----------- << imports@AAAAAAGXfC8vELz95T4= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXfC8vELz95T4= >>
// ----------- >>
public class IMembresiaRepositoriolmpl implements IMembresiaRepositorio {
    /**
    * @param Membresia membresia
    */

    @Override
    // ----------- << method.annotations@AAAAAAGXfD8cBC7UTfw= >>
    // ----------- >>
    public void guardar(void Membresia membresia) {
    // ----------- << method.body@AAAAAAGXfD8cBC7UTfw= >>
    // ----------- >>
    }
    /**
    * @param Membresia membresia
    */

    @Override
    // ----------- << method.annotations@AAAAAAGXfD+6a4bdaqw= >>
    // ----------- >>
    public void actualizar(void Membresia membresia) {
    // ----------- << method.body@AAAAAAGXfD+6a4bdaqw= >>
    // ----------- >>
    }
    /**
    * @param String id
    */

    @Override
    // ----------- << method.annotations@AAAAAAGXfD/VmovGtzE= >>
    // ----------- >>
    public void eliminarPorId(void String id) {
    // ----------- << method.body@AAAAAAGXfD/VmovGtzE= >>
    // ----------- >>
    }
    /**
    * @param String id
    */

    @Override
    // ----------- << method.annotations@AAAAAAGXfD/qXo+/KtQ= >>
    // ----------- >>
    public void buscarPorId(void String id) {
    // ----------- << method.body@AAAAAAGXfD/qXo+/KtQ= >>
    // ----------- >>
    }
    @Override
    // ----------- << method.annotations@AAAAAAGXfEIHVelmf98= >>
    // ----------- >>
    public void listarTodas() {
    // ----------- << method.body@AAAAAAGXfEIHVelmf98= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGXfC8vELz95T4= >>
// ----------- >>
}