/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Repositorio.mysql;

import java.util.*;
import java.time.*;


import Dominio.Notificaciones.INotificacionRepositorio;
// ----------- << imports@AAAAAAGXfDFnMBXz4OA= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXfDFnMBXz4OA= >>
// ----------- >>
public class INotificacionRepositoriolmpl implements INotificacionRepositorio {
    /**
    * @param Notificacion n
    */

    @Override
    // ----------- << method.annotations@AAAAAAGXfEVxAP69vEg= >>
    // ----------- >>
    public void guardar(void Notificacion n) {
    // ----------- << method.body@AAAAAAGXfEVxAP69vEg= >>
    // ----------- >>
    }
    /**
    * @param Notificacion n
    */

    @Override
    // ----------- << method.annotations@AAAAAAGXfEWA6AEGIbQ= >>
    // ----------- >>
    public void actualizar(void Notificacion n) {
    // ----------- << method.body@AAAAAAGXfEWA6AEGIbQ= >>
    // ----------- >>
    }
    @Override
    // ----------- << method.annotations@AAAAAAGXfEX6dAXv6Tc= >>
    // ----------- >>
    public void listarTodas() {
    // ----------- << method.body@AAAAAAGXfEX6dAXv6Tc= >>
    // ----------- >>
    }
    /**
    * @param String id
    */

    @Override
    // ----------- << method.annotations@AAAAAAGXfEYe+Ay2+ho= >>
    // ----------- >>
    public void buscarPorId(void String id) {
    // ----------- << method.body@AAAAAAGXfEYe+Ay2+ho= >>
    // ----------- >>
    }
    /**
    * @param String id
    */

    @Override
    // ----------- << method.annotations@AAAAAAGXfEZEpBGfvZs= >>
    // ----------- >>
    public void eliminarPorId(void String id) {
    // ----------- << method.body@AAAAAAGXfEZEpBGfvZs= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGXfDFnMBXz4OA= >>
// ----------- >>
}