/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Repositorio.mysql;

import java.util.*;
import java.time.*;


import Dominio.Rutinas.IRutinaRepositorio;
// ----------- << imports@AAAAAAGXfC80s78Gya4= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXfC80s78Gya4= >>
// ----------- >>
public class IRutinaRepositoriolmpl implements IRutinaRepositorio {
    /**
    * @param Rutina rutina
    */

    @Override
    // ----------- << method.annotations@AAAAAAGXfEE5U9SbAuQ= >>
    // ----------- >>
    public void guardar(void Rutina rutina) {
    // ----------- << method.body@AAAAAAGXfEE5U9SbAuQ= >>
    // ----------- >>
    }
    /**
    * @param Rutina rutina
    */

    @Override
    // ----------- << method.annotations@AAAAAAGXfEE+xNbkIAw= >>
    // ----------- >>
    public void actualizar(void Rutina rutina) {
    // ----------- << method.body@AAAAAAGXfEE+xNbkIAw= >>
    // ----------- >>
    }
    /**
    * @param String id
    */

    @Override
    // ----------- << method.annotations@AAAAAAGXfEFcR9kt/ns= >>
    // ----------- >>
    public void eliminarPorId(void String id) {
    // ----------- << method.body@AAAAAAGXfEFcR9kt/ns= >>
    // ----------- >>
    }
    /**
    * @param String id
    */

    @Override
    // ----------- << method.annotations@AAAAAAGXfEFu8dt2C9Q= >>
    // ----------- >>
    public void buscarPorId(void String id) {
    // ----------- << method.body@AAAAAAGXfEFu8dt2C9Q= >>
    // ----------- >>
    }
    @Override
    // ----------- << method.annotations@AAAAAAGXfEG5Jd2/erE= >>
    // ----------- >>
    public void listarTodas() {
    // ----------- << method.body@AAAAAAGXfEG5Jd2/erE= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGXfC80s78Gya4= >>
// ----------- >>
}