/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Repositorio.mysql;

import java.util.*;
import java.time.*;


import Dominio.Sesiones.ISesionRepositorio;
// ----------- << imports@AAAAAAGXfC986dttMa4= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXfC986dttMa4= >>
// ----------- >>
public class ISesionRepositoriolmpl implements ISesionRepositorio {
    /**
    * @param Sesion s
    */

    @Override
    // ----------- << method.annotations@AAAAAAGXfEmsCEmKAsI= >>
    // ----------- >>
    public void guardar(void Sesion s) {
    // ----------- << method.body@AAAAAAGXfEmsCEmKAsI= >>
    // ----------- >>
    }
    /**
    * @param Sesion s
    */

    @Override
    // ----------- << method.annotations@AAAAAAGXfEm8cEvTD2c= >>
    // ----------- >>
    public void actualizar(void Sesion s) {
    // ----------- << method.body@AAAAAAGXfEm8cEvTD2c= >>
    // ----------- >>
    }
    /**
    * @param String id
    */

    @Override
    // ----------- << method.annotations@AAAAAAGXfEnPlE4cLGA= >>
    // ----------- >>
    public void eliminarPorId(void String id) {
    // ----------- << method.body@AAAAAAGXfEnPlE4cLGA= >>
    // ----------- >>
    }
    /**
    * @param String id
    */

    @Override
    // ----------- << method.annotations@AAAAAAGXfEndvFBl2M8= >>
    // ----------- >>
    public void buscarPorId(void String id) {
    // ----------- << method.body@AAAAAAGXfEndvFBl2M8= >>
    // ----------- >>
    }
    @Override
    // ----------- << method.annotations@AAAAAAGXfEnrHVKuPgg= >>
    // ----------- >>
    public void listarTodas() {
    // ----------- << method.body@AAAAAAGXfEnrHVKuPgg= >>
    // ----------- >>
    }
    /**
    * @param String clienteId
    */

    @Override
    // ----------- << method.annotations@AAAAAAGXfEoMvFTFHNg= >>
    // ----------- >>
    public void listarPorCliente(void String clienteId) {
    // ----------- << method.body@AAAAAAGXfEoMvFTFHNg= >>
    // ----------- >>
    }
    /**
    * @param String entrenadorId
    */

    @Override
    // ----------- << method.annotations@AAAAAAGXfEoblFcOeOA= >>
    // ----------- >>
    public void listarPorEntrenador(void String entrenadorId) {
    // ----------- << method.body@AAAAAAGXfEoblFcOeOA= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGXfC986dttMa4= >>
// ----------- >>
}