/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Repositorio.mysql;

import java.util.*;
import java.time.*;


import Dominio.Usuarios.IUsuarioRepositorio;
// ----------- << imports@AAAAAAGXfC8j97oE5jc= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXfC8j97oE5jc= >>
// ----------- >>
public class IUsuarioRepositoriolmpl implements IUsuarioRepositorio {
    /**
    * @param Usuario usuario
    */

    @Override
    // ----------- << method.annotations@AAAAAAGXfD1KmMda8Jk= >>
    // ----------- >>
    public void guardar(void Usuario usuario) {
    // ----------- << method.body@AAAAAAGXfD1KmMda8Jk= >>
    // ----------- >>
    }
    /**
    * @param Usuario usuario
    */

    @Override
    // ----------- << method.annotations@AAAAAAGXfD1py8xDeC8= >>
    // ----------- >>
    public void actualizar(void Usuario usuario) {
    // ----------- << method.body@AAAAAAGXfD1py8xDeC8= >>
    // ----------- >>
    }
    /**
    * @param String id
    */

    @Override
    // ----------- << method.annotations@AAAAAAGXfD2lE9Esysg= >>
    // ----------- >>
    public void eliminarPorId(void String id) {
    // ----------- << method.body@AAAAAAGXfD2lE9Esysg= >>
    // ----------- >>
    }
    /**
    * @param String id
    */

    @Override
    // ----------- << method.annotations@AAAAAAGXfD274dZ1hWc= >>
    // ----------- >>
    public void buscarPorId(void String id) {
    // ----------- << method.body@AAAAAAGXfD274dZ1hWc= >>
    // ----------- >>
    }
    @Override
    // ----------- << method.annotations@AAAAAAGXfEIrgfBeogo= >>
    // ----------- >>
    public void listarTodos() {
    // ----------- << method.body@AAAAAAGXfEIrgfBeogo= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGXfC8j97oE5jc= >>
// ----------- >>
}