/*
 * This code has been generated by the Javazzar: a code generator for modern Java.
 *
 * Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
 */
package com.soft.GymApp.Repositorio.mysql;


//public class IUsuarioRepositoriolmpl implements IUsuarioRepositorio {
//    @Override
//    public void guardar(Usuario usuario) {
//
//    }
//
//    @Override
//    public void actualizar(Usuario usuario) {
//
//    }
//
//    @Override
//    public void eliminarPorId(String id) {
//
//    }
//
//    @Override
//    public void buscarPorId(String id) {
//
//    }
//
//    @Override
//    public void listarTodos() {
//
//    }
//
//}