/*
 * This code has been generated by the Javazzar: a code generator for modern Java.
 *
 * Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
 */
package com.cancheros.GymApp.Repositorio.mysql;

import com.cancheros.GymApp.Dominio.Usuarios.IUsuarioRepositorio;
import com.cancheros.GymApp.Dominio.Usuarios.Usuario;

import java.util.*;
import java.time.*;


public class IUsuarioRepositoriolmpl implements IUsuarioRepositorio {
    @Override
    public void guardar(Usuario usuario) {

    }

    @Override
    public void actualizar(Usuario usuario) {

    }

    @Override
    public void eliminarPorId(String id) {

    }

    @Override
    public void buscarPorId(String id) {

    }

    @Override
    public void listarTodos() {

    }

}