/*
 * This code has been generated by the Javazzar: a code generator for modern Java.
 *
 * Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
 */
package com.soft.gymapp.dominio.sesiones;

import com.soft.gymapp.dominio.membresias.EstadoMembresia;
import com.soft.gymapp.dominio.usuarios.Cliente;
import com.soft.gymapp.dominio.usuarios.Entrenador;
import jakarta.persistence.*;

import java.util.*;


@Entity
@Table(name = "sesion")
public class Sesion {
    @Id
    private int id;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private EstadoSesion estado;

    @ManyToMany
    private List<Cliente> clientes = new ArrayList<>();

    @ManyToOne
    private Entrenador Entrenador;

    @Embedded
    private Horario horario;

    @ManyToOne
    private Sala Sala;

    public void confirmar() {
        this.estado = EstadoSesion.EnProgreso;
    }

    public void cancelar() {
        this.estado = EstadoSesion.Terminada;
    }

    public void reprogramar(Horario nuevoHorario) {
        this.horario = nuevoHorario;
        this.estado = EstadoSesion.SinEmpezar;
    }

    // Getters
    public int getId() {
        return id;
    }
    public EstadoSesion getEstado() {
        return estado;
    }
    public List<Cliente> getClientes() {
        return clientes;
    }
    public Entrenador getEntrenador() {
        return entrenador;
    }
    public Horario getHorario() {
        return horario;
    }
    public Sala getSala() {
        return sala;
    }
}