/*
 * This code has been generated by the Javazzar: a code generator for modern Java.
 *
 * Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
 */
package com.soft.gymapp.dominio.sesiones;

import com.soft.gymapp.dominio.usuarios.Cliente;
import com.soft.gymapp.dominio.usuarios.Entrenador;
import jakarta.persistence.*;

import java.util.*;


@Entity
@Table(name = "sesion")
public class Sesion {
    @Id
    private int id;
    private String estado;

    @ManyToMany
    private List<Cliente> clientes = new ArrayList<>();

    @ManyToOne
    private Entrenador Entrenador;

    @Embedded
    private Horario horario;

    @ManyToOne
    private Sala Sala;

    public void confirmar() {

    }


    public void cancelar() {

    }

    public void reprogramar(Horario nuevoHorario) {

    }
}