/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Presentation.Controladores;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGXe+NepscyjP8= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXe+NepscyjP8= >>
// ----------- >>
public class MembresiaController {
    // ----------- << method.annotations@AAAAAAGXe+gSI6jPunY= >>
    // ----------- >>
    public void listarMembresias() {
    // ----------- << method.body@AAAAAAGXe+gSI6jPunY= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGXe+glA62GOWI= >>
    // ----------- >>
    public void crearMembresia() {
    // ----------- << method.body@AAAAAAGXe+glA62GOWI= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGXe+hCcbVtmS4= >>
    // ----------- >>
    public void asignarMembresiaAUsuario() {
    // ----------- << method.body@AAAAAAGXe+hCcbVtmS4= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGXe+hT8bokdrk= >>
    // ----------- >>
    public void cancelarMembresia() {
    // ----------- << method.body@AAAAAAGXe+hT8bokdrk= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGXe+NepscyjP8= >>
// ----------- >>
}