/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Presentation.Controladores;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGXe+Nnp8hVon0= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXe+Nnp8hVon0= >>
// ----------- >>
public class NotificacionController {
    // ----------- << method.annotations@AAAAAAGXe+k/mBKrQ4M= >>
    // ----------- >>
    public void enviarNotificacion() {
    // ----------- << method.body@AAAAAAGXe+k/mBKrQ4M= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGXe+lTGBdiiKs= >>
    // ----------- >>
    public void listarNotificacionesUsuario() {
    // ----------- << method.body@AAAAAAGXe+lTGBdiiKs= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGXe+Nnp8hVon0= >>
// ----------- >>
}