/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Presentation.Controladores;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGXe+N44cqb+P0= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXe+N44cqb+P0= >>
// ----------- >>
public class RutinaController {
    // ----------- << method.annotations@AAAAAAGXe+h1pNJdwSA= >>
    // ----------- >>
    public void crearRutina() {
    // ----------- << method.body@AAAAAAGXe+h1pNJdwSA= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGXe+ib2dcUUmk= >>
    // ----------- >>
    public void asignarRutinaACliente() {
    // ----------- << method.body@AAAAAAGXe+ib2dcUUmk= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGXe+i5jdvLNXQ= >>
    // ----------- >>
    public void modificarRutina() {
    // ----------- << method.body@AAAAAAGXe+i5jdvLNXQ= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGXe+N44cqb+P0= >>
// ----------- >>
}