/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Presentation.Controladores;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGXe+NwGsl4/dU= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXe+NwGsl4/dU= >>
// ----------- >>
public class SesionController {
    // ----------- << method.annotations@AAAAAAGXe+jyhP0EX/A= >>
    // ----------- >>
    public void programarSesion() {
    // ----------- << method.body@AAAAAAGXe+jyhP0EX/A= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGXe+kJNwJ7gKg= >>
    // ----------- >>
    public void cancelarSesion() {
    // ----------- << method.body@AAAAAAGXe+kJNwJ7gKg= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGXe+kcrwcy8ls= >>
    // ----------- >>
    public void listarSesionesPorUsuario() {
    // ----------- << method.body@AAAAAAGXe+kcrwcy8ls= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGXe+NwGsl4/dU= >>
// ----------- >>
}