/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Presentation.Controladores;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGXe+M2+sYPrYw= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXe+M2+sYPrYw= >>
// ----------- >>
public class UsuarioController {
    // ----------- << method.annotations@AAAAAAGXe+VamFGgEW8= >>
    // ----------- >>
    public void registrarUsuario() {
    // ----------- << method.body@AAAAAAGXe+VamFGgEW8= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGXe+WKuFa3X/M= >>
    // ----------- >>
    public void editarPerfil() {
    // ----------- << method.body@AAAAAAGXe+WKuFa3X/M= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGXe+WgUFtuc0Y= >>
    // ----------- >>
    public void iniciarSesion() {
    // ----------- << method.body@AAAAAAGXe+WgUFtuc0Y= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGXe+XDPmTVXWs= >>
    // ----------- >>
    public void cerrarSesion() {
    // ----------- << method.body@AAAAAAGXe+XDPmTVXWs= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGXe+M2+sYPrYw= >>
// ----------- >>
}