/*
 * This code has been generated by the Javazzar: a code generator for modern Java.
 *
 * Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
 */
package com.cancheros.GymApp.Dominio.Sesiones;

import com.cancheros.GymApp.Dominio.Rutinas.Ejercicio;
import com.cancheros.GymApp.Dominio.Usuarios.Cliente;
import com.cancheros.GymApp.Dominio.Usuarios.Entrenador;
import jakarta.persistence.*;

import java.util.*;
import java.time.*;


@Entity
@Table(name = "sesion")
public class Sesion {
    @Id
    private int id;
    private String estado;

    @ManyToMany
    private List<Cliente> clientes = new ArrayList<>();

    @ManyToOne
    private Entrenador Entrenador;

    @Embedded
    private Horario horario;

    @ManyToOne
    private Sala Sala;

    public void confirmar() {

    }


    public void cancelar() {

    }

    public void reprogramar(Horario nuevoHorario) {

    }
}