/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Dominio.Sesiones;

import java.util.*;
import java.time.*;


import domain.Sesion;
import persistence.Sesion;
// ----------- << imports@AAAAAAGXU6vKZ8nwzp4= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXU6vKZ8nwzp4= >>
// ----------- >>
public class Horario {
    // ----------- << attribute.annotations@AAAAAAGXU6zDPNOwPqI= >>
    // ----------- >>
    private Date fecha;

    // ----------- << attribute.annotations@AAAAAAGXU6zXPNVMCNc= >>
    // ----------- >>
    private Time horaInicio;

    // ----------- << attribute.annotations@AAAAAAGXU6zpB9c5jDQ= >>
    // ----------- >>
    private Time horaFin;

    // ----------- << attribute.annotations@AAAAAAGXU7C08CaepF8= >>
    // ----------- >>
    private Sesion sesion;

    // ----------- << attribute.annotations@AAAAAAGXej9BzqYIF7w= >>
    // ----------- >>
    private Sesion ;

    // ----------- << attribute.annotations@AAAAAAGXej9BzqY4LPE= >>
    // ----------- >>
    private Sesion ;

    public Date getFecha() {
        return fecha;
    }

    public Time getHoraInicio() {
        return horaInicio;
    }

    public Time getHoraFin() {
        return horaFin;
    }

    public Sesion getSesion() {
        return sesion;
    }

    public Sesion get() {
        return ;
    }

    public Sesion get() {
        return ;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public void setHoraInicio(Time horaInicio) {
        this.horaInicio = horaInicio;
    }

    public void setHoraFin(Time horaFin) {
        this.horaFin = horaFin;
    }

    public void setSesion(Sesion sesion) {
        this.sesion = sesion;
    }

    public void set(Sesion ) {
        this. = ;
    }

    public void set(Sesion ) {
        this. = ;
    }

    public void linkSesion(Sesion _sesion) {
        if (_sesion != null) {
            _sesion.unlinkHorario();
            _sesion.setHorario(this);
        }

        unlinkSesion();
        setSesion(_sesion);
    }

    public void link(Sesion _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Sesion _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlinkSesion() {
        if (getSesion() != null) {
            getSesion().setHorario(null);
            setSesion(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAGXU7ylc+OZw3M= >>
    // ----------- >>
    public boolean esDisponible() {
    // ----------- << method.body@AAAAAAGXU7ylc+OZw3M= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGXU6vKZ8nwzp4= >>
// ----------- >>
}