/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Dominio.Sesiones;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGXfEagODJ8tLw= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXfEagODJ8tLw= >>
// ----------- >>
public interface ISesionRepositorio {
    /**
    * @param Sesion s
    */

    // ----------- << method.annotations@AAAAAAGXfEmsCEmKAsI= >>
    // ----------- >>
    void guardar(void Sesion s);
    /**
    * @param Sesion s
    */

    // ----------- << method.annotations@AAAAAAGXfEm8cEvTD2c= >>
    // ----------- >>
    void actualizar(void Sesion s);
    /**
    * @param String id
    */

    // ----------- << method.annotations@AAAAAAGXfEnPlE4cLGA= >>
    // ----------- >>
    void eliminarPorId(void String id);
    /**
    * @param String id
    */

    // ----------- << method.annotations@AAAAAAGXfEndvFBl2M8= >>
    // ----------- >>
    void buscarPorId(void String id);
    // ----------- << method.annotations@AAAAAAGXfEnrHVKuPgg= >>
    // ----------- >>
    void listarTodas();
    /**
    * @param String clienteId
    */

    // ----------- << method.annotations@AAAAAAGXfEoMvFTFHNg= >>
    // ----------- >>
    void listarPorCliente(void String clienteId);
    /**
    * @param String entrenadorId
    */

    // ----------- << method.annotations@AAAAAAGXfEoblFcOeOA= >>
    // ----------- >>
    void listarPorEntrenador(void String entrenadorId);
// ----------- << interface.extras@AAAAAAGXfEagODJ8tLw= >>
// ----------- >>
}