/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Dominio.Sesiones;

import java.util.*;
import java.time.*;


import domain.Sesion;
import persistence.Sesion;
// ----------- << imports@AAAAAAGXU6vTbspEG40= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXU6vTbspEG40= >>
// ----------- >>
public class Sala {
    // ----------- << attribute.annotations@AAAAAAGXU6z+VtkLLHc= >>
    // ----------- >>
    private int id;

    // ----------- << attribute.annotations@AAAAAAGXU60O1NqnVqs= >>
    // ----------- >>
    private String nombre;

    // ----------- << attribute.annotations@AAAAAAGXU60e+dxDDe8= >>
    // ----------- >>
    private int capacidad;

    // ----------- << attribute.annotations@AAAAAAGXU7DXqj14PRE= >>
    // ----------- >>
    private Sesion Sesion;

    // ----------- << attribute.annotations@AAAAAAGXej9BzqYLPNI= >>
    // ----------- >>
    private Sesion ;

    // ----------- << attribute.annotations@AAAAAAGXej9BzqY768M= >>
    // ----------- >>
    private Sesion ;

    public int getId() {
        return id;
    }

    public String getNombre() {
        return nombre;
    }

    public int getCapacidad() {
        return capacidad;
    }

    public Sesion getSesion() {
        return Sesion;
    }

    public Sesion get() {
        return ;
    }

    public Sesion get() {
        return ;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public void setCapacidad(int capacidad) {
        this.capacidad = capacidad;
    }

    public void setSesion(Sesion Sesion) {
        this.Sesion = Sesion;
    }

    public void set(Sesion ) {
        this. = ;
    }

    public void set(Sesion ) {
        this. = ;
    }

    public void linkSesion(Sesion _Sesion) {
        if (_Sesion != null) {
            _Sesion.unlinkSala();
            _Sesion.setSala(this);
        }

        unlinkSesion();
        setSesion(_Sesion);
    }

    public void link(Sesion _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Sesion _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlinkSesion() {
        if (getSesion() != null) {
            getSesion().setSala(null);
            setSesion(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    /**
    * @param fecha
    */

    // ----------- << method.annotations@AAAAAAGXU7y/DeokGNQ= >>
    // ----------- >>
    public boolean verDisponibilidad(Date fecha) {
    // ----------- << method.body@AAAAAAGXU7y/DeokGNQ= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGXU6vTbspEG40= >>
// ----------- >>
}