/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Dominio.Sesiones;

import java.util.*;
import java.time.*;


import Dominio.Usuarios.Cliente;
import Dominio.Usuarios.Entrenador;
import Usuarios.Cliente;
import Usuarios.Entrenador;
import domain.Cliente;
import domain.Entrenador;
import domain.Usuarios.Cliente;
import domain.Usuarios.Entrenador;
// ----------- << imports@AAAAAAGXU6uypMm34E0= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXU6uypMm34E0= >>
// ----------- >>
public class Sesion {
    // ----------- << attribute.annotations@AAAAAAGXU6x+hM5wpTE= >>
    // ----------- >>
    private int id;

    // ----------- << attribute.annotations@AAAAAAGXU6ykjtIUGCk= >>
    // ----------- >>
    private String estado;

    // ----------- << attribute.annotations@AAAAAAGXU64BDuyJgBc= >>
    // ----------- >>
    private Cliente ;

    // ----------- << attribute.annotations@AAAAAAGXU659jfzMlzE= >>
    // ----------- >>
    private Entrenador Entrenador;

    // ----------- << attribute.annotations@AAAAAAGXU7C08CafZpQ= >>
    // ----------- >>
    private Horario horario;

    // ----------- << attribute.annotations@AAAAAAGXU7DXqj15mz8= >>
    // ----------- >>
    private Sala Sala;

    // ----------- << attribute.annotations@AAAAAAGXej9BzaXQzy4= >>
    // ----------- >>
    private Cliente ;

    // ----------- << attribute.annotations@AAAAAAGXej9BzaXbY+8= >>
    // ----------- >>
    private Entrenador ;

    // ----------- << attribute.annotations@AAAAAAGXey7DgrMDArg= >>
    // ----------- >>
    private Cliente ;

    // ----------- << attribute.annotations@AAAAAAGXey7DgrMUA8Q= >>
    // ----------- >>
    private Entrenador ;

    // ----------- << attribute.annotations@AAAAAAGXeoVZIVuujzg= >>
    // ----------- >>
    private Cliente ;

    // ----------- << attribute.annotations@AAAAAAGXeoVZIVu60pQ= >>
    // ----------- >>
    private Entrenador ;

    public int getId() {
        return id;
    }

    public String getEstado() {
        return estado;
    }

    public Cliente get() {
        return ;
    }

    public Entrenador getEntrenador() {
        return Entrenador;
    }

    public Horario getHorario() {
        return horario;
    }

    public Sala getSala() {
        return Sala;
    }

    public Cliente get() {
        return ;
    }

    public Entrenador get() {
        return ;
    }

    public Cliente get() {
        return ;
    }

    public Entrenador get() {
        return ;
    }

    public Cliente get() {
        return ;
    }

    public Entrenador get() {
        return ;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public void set(Cliente ) {
        this. = ;
    }

    public void setEntrenador(Entrenador Entrenador) {
        this.Entrenador = Entrenador;
    }

    public void setHorario(Horario horario) {
        this.horario = horario;
    }

    public void setSala(Sala Sala) {
        this.Sala = Sala;
    }

    public void set(Cliente ) {
        this. = ;
    }

    public void set(Entrenador ) {
        this. = ;
    }

    public void set(Cliente ) {
        this. = ;
    }

    public void set(Entrenador ) {
        this. = ;
    }

    public void set(Cliente ) {
        this. = ;
    }

    public void set(Entrenador ) {
        this. = ;
    }

    public void link(Cliente _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void linkEntrenador(Entrenador _Entrenador) {
        if (_Entrenador != null) {
            _Entrenador.unlinkSesion();
            _Entrenador.setSesion(this);
        }

        unlinkEntrenador();
        setEntrenador(_Entrenador);
    }

    public void linkHorario(Horario _horario) {
        if (_horario != null) {
            _horario.unlinkSesion();
            _horario.setSesion(this);
        }

        unlinkHorario();
        setHorario(_horario);
    }

    public void linkSala(Sala _Sala) {
        if (_Sala != null) {
            _Sala.unlinkSesion();
            _Sala.setSesion(this);
        }

        unlinkSala();
        setSala(_Sala);
    }

    public void link(Cliente _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Entrenador _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Cliente _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Entrenador _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Cliente _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Entrenador _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlinkEntrenador() {
        if (getEntrenador() != null) {
            getEntrenador().setSesion(null);
            setEntrenador(null);
        }
    }

    public void unlinkHorario() {
        if (getHorario() != null) {
            getHorario().setSesion(null);
            setHorario(null);
        }
    }

    public void unlinkSala() {
        if (getSala() != null) {
            getSala().setSesion(null);
            setSala(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAGXU7xpdNs/pdc= >>
    // ----------- >>
    public void confirmar() {
    // ----------- << method.body@AAAAAAGXU7xpdNs/pdc= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGXU7x/Bd4WT34= >>
    // ----------- >>
    public void cancelar() {
    // ----------- << method.body@AAAAAAGXU7x/Bd4WT34= >>
    // ----------- >>
    }
    /**
    * @param nuevoHorario
    */

    // ----------- << method.annotations@AAAAAAGXU7yQq+DAAOU= >>
    // ----------- >>
    public void reprogramar(Horario nuevoHorario) {
    // ----------- << method.body@AAAAAAGXU7yQq+DAAOU= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGXU6uypMm34E0= >>
// ----------- >>
}