/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Dominio.Notificaciones;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGXfETeu8r67VM= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXfETeu8r67VM= >>
// ----------- >>
public interface INotificacionRepositorio {
    /**
    * @param Notificacion n
    */

    // ----------- << method.annotations@AAAAAAGXfEVxAP69vEg= >>
    // ----------- >>
    void guardar(void Notificacion n);
    /**
    * @param Notificacion n
    */

    // ----------- << method.annotations@AAAAAAGXfEWA6AEGIbQ= >>
    // ----------- >>
    void actualizar(void Notificacion n);
    // ----------- << method.annotations@AAAAAAGXfEX6dAXv6Tc= >>
    // ----------- >>
    void listarTodas();
    /**
    * @param String id
    */

    // ----------- << method.annotations@AAAAAAGXfEYe+Ay2+ho= >>
    // ----------- >>
    void buscarPorId(void String id);
    /**
    * @param String id
    */

    // ----------- << method.annotations@AAAAAAGXfEZEpBGfvZs= >>
    // ----------- >>
    void eliminarPorId(void String id);
// ----------- << interface.extras@AAAAAAGXfETeu8r67VM= >>
// ----------- >>
}