/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Dominio.Notificaciones;

import java.util.*;
import java.time.*;


import Dominio.Usuarios.Usuario;
import Usuarios.Usuario;
import domain.Usuario;
import domain.Usuarios.Usuario;
import persistence.Usuario;
// ----------- << imports@AAAAAAGXU7Nmkvdb8h8= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXU7Nmkvdb8h8= >>
// ----------- >>
public class Notificacion {
    // ----------- << attribute.annotations@AAAAAAGXU7QDyQYt+n0= >>
    // ----------- >>
    private int id;

    // ----------- << attribute.annotations@AAAAAAGXU7QWAwh9G1g= >>
    // ----------- >>
    private String mensaje;

    // ----------- << attribute.annotations@AAAAAAGXU7QmsgrN4vA= >>
    // ----------- >>
    private Date fechaEnvio;

    // ----------- << attribute.annotations@AAAAAAGXU7Q4ug0dUmE= >>
    // ----------- >>
    private boolean leido;

    // ----------- << attribute.annotations@AAAAAAGXU7TZsy9VmCc= >>
    // ----------- >>
    private Usuario Usuario;

    // ----------- << attribute.annotations@AAAAAAGXU7Vkezz/FGc= >>
    // ----------- >>
    private TipoNotificacion TipoNotificacion;

    // ----------- << attribute.annotations@AAAAAAGXej9BzaW+5YQ= >>
    // ----------- >>
    private Usuario ;

    // ----------- << attribute.annotations@AAAAAAGXey7DgrMfJn0= >>
    // ----------- >>
    private Usuario ;

    // ----------- << attribute.annotations@AAAAAAGXej9BzqYd9Cg= >>
    // ----------- >>
    private Usuario ;

    // ----------- << attribute.annotations@AAAAAAGXeoVZIVubwHY= >>
    // ----------- >>
    private Usuario ;

    public int getId() {
        return id;
    }

    public String getMensaje() {
        return mensaje;
    }

    public Date getFechaEnvio() {
        return fechaEnvio;
    }

    public boolean isLeido() {
        return leido;
    }

    public Usuario getUsuario() {
        return Usuario;
    }

    public TipoNotificacion getTipoNotificacion() {
        return TipoNotificacion;
    }

    public Usuario get() {
        return ;
    }

    public Usuario get() {
        return ;
    }

    public Usuario get() {
        return ;
    }

    public Usuario get() {
        return ;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }

    public void setFechaEnvio(Date fechaEnvio) {
        this.fechaEnvio = fechaEnvio;
    }

    public void setLeido(boolean leido) {
        this.leido = leido;
    }

    public void setUsuario(Usuario Usuario) {
        this.Usuario = Usuario;
    }

    public void setTipoNotificacion(TipoNotificacion TipoNotificacion) {
        this.TipoNotificacion = TipoNotificacion;
    }

    public void set(Usuario ) {
        this. = ;
    }

    public void set(Usuario ) {
        this. = ;
    }

    public void set(Usuario ) {
        this. = ;
    }

    public void set(Usuario ) {
        this. = ;
    }

    public void linkUsuario(Usuario _Usuario) {
        if (_Usuario != null) {
            _Usuario.unlinkNotificacion();
            _Usuario.setNotificacion(this);
        }

        unlinkUsuario();
        setUsuario(_Usuario);
    }

    public void linkTipoNotificacion(TipoNotificacion _TipoNotificacion) {
        if (_TipoNotificacion != null) {
            _TipoNotificacion.unlinkNotificacion();
            _TipoNotificacion.setNotificacion(this);
        }

        unlinkTipoNotificacion();
        setTipoNotificacion(_TipoNotificacion);
    }

    public void link(Usuario _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Usuario _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Usuario _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Usuario _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlinkUsuario() {
        if (getUsuario() != null) {
            getUsuario().setNotificacion(null);
            setUsuario(null);
        }
    }

    public void unlinkTipoNotificacion() {
        if (getTipoNotificacion() != null) {
            getTipoNotificacion().setNotificacion(null);
            setTipoNotificacion(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAGXU70IhyERXjo= >>
    // ----------- >>
    public void marcarComoLeida() {
    // ----------- << method.body@AAAAAAGXU70IhyERXjo= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGXU70mQSO7eQQ= >>
    // ----------- >>
    public void enviar() {
    // ----------- << method.body@AAAAAAGXU70mQSO7eQQ= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGXU7Nmkvdb8h8= >>
// ----------- >>
}