/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Dominio.Notificaciones;

import java.util.*;
import java.time.*;


import application.Notificacion;
import domain.Notificacion;
// ----------- << imports@AAAAAAGXU7OY7fesnFA= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXU7OY7fesnFA= >>
// ----------- >>
public class TipoNotificacion {
    // ----------- << attribute.annotations@AAAAAAGXU7RLfg9t44g= >>
    // ----------- >>
    private int id;

    // ----------- << attribute.annotations@AAAAAAGXU7RbpxG9Hac= >>
    // ----------- >>
    private String nombre;

    // ----------- << attribute.annotations@AAAAAAGXU7Vkezz+Z/U= >>
    // ----------- >>
    private Notificacion Notificacion;

    // ----------- << attribute.annotations@AAAAAAGXej9BzaX+IFA= >>
    // ----------- >>
    private Notificacion tiene;

    // ----------- << attribute.annotations@AAAAAAGXej9BzqZ1/SQ= >>
    // ----------- >>
    private Notificacion tiene;

    public int getId() {
        return id;
    }

    public String getNombre() {
        return nombre;
    }

    public Notificacion getNotificacion() {
        return Notificacion;
    }

    public Notificacion getTiene() {
        return tiene;
    }

    public Notificacion getTiene() {
        return tiene;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public void setNotificacion(Notificacion Notificacion) {
        this.Notificacion = Notificacion;
    }

    public void setTiene(Notificacion tiene) {
        this.tiene = tiene;
    }

    public void setTiene(Notificacion tiene) {
        this.tiene = tiene;
    }

    public void linkNotificacion(Notificacion _Notificacion) {
        if (_Notificacion != null) {
            _Notificacion.unlinkTipoNotificacion();
            _Notificacion.setTipoNotificacion(this);
        }

        unlinkNotificacion();
        setNotificacion(_Notificacion);
    }

    public void linkTiene(Notificacion _tiene) {
        if (_tiene != null) {
            _tiene.unlink();
            _tiene.set(this);
        }

        unlinkTiene();
        setTiene(_tiene);
    }

    public void linkTiene(Notificacion _tiene) {
        if (_tiene != null) {
            _tiene.unlink();
            _tiene.set(this);
        }

        unlinkTiene();
        setTiene(_tiene);
    }

    public void unlinkNotificacion() {
        if (getNotificacion() != null) {
            getNotificacion().setTipoNotificacion(null);
            setNotificacion(null);
        }
    }

    public void unlinkTiene() {
        if (getTiene() != null) {
            getTiene().set(null);
            setTiene(null);
        }
    }

    public void unlinkTiene() {
        if (getTiene() != null) {
            getTiene().set(null);
            setTiene(null);
        }
    }

// ----------- << class.extras@AAAAAAGXU7OY7fesnFA= >>
// ----------- >>
}