/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Dominio.Usuarios;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGXU0yNFKOFQgw= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXU0yNFKOFQgw= >>
// ----------- >>
public class Administrador extends Usuario {
    // ----------- << attribute.annotations@AAAAAAGXU7f+lJ3JPOI= >>
    // ----------- >>
    private String rol;

    public String getRol() {
        return rol;
    }

    public void setRol(String rol) {
        this.rol = rol;
    }

    // ----------- << method.annotations@AAAAAAGXU7nPeGeShOg= >>
    // ----------- >>
    public void gestionarUsuarios() {
    // ----------- << method.body@AAAAAAGXU7nPeGeShOg= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGXU7nz0Wo8Zw8= >>
    // ----------- >>
    public void verReportes() {
    // ----------- << method.body@AAAAAAGXU7nz0Wo8Zw8= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGXU0yNFKOFQgw= >>
// ----------- >>
}