/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Dominio.Usuarios;

import java.util.*;
import java.time.*;


import Dominio.Membresías.Membresia;
import Dominio.Rutinas.PlanEntrenamiento;
import Dominio.Sesiones.Sesion;
// ----------- << imports@AAAAAAGXU0vS8aN9XoE= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXU0vS8aN9XoE= >>
// ----------- >>
public class Cliente extends Usuario {
    // ----------- << attribute.annotations@AAAAAAGXU7b2bVo3/v8= >>
    // ----------- >>
    private String objetivo;

    // ----------- << attribute.annotations@AAAAAAGXU7cfblyHiIM= >>
    // ----------- >>
    private String nivel;

    // ----------- << attribute.annotations@AAAAAAGXU53byAawTuI= >>
    // ----------- >>
    private Membresia Membresia;

    // ----------- << attribute.annotations@AAAAAAGXU6huE6YnHhM= >>
    // ----------- >>
    private PlanEntrenamiento PlanEntrenamiento;

    // ----------- << attribute.annotations@AAAAAAGXU64BDuyKCEA= >>
    // ----------- >>
    private Sesion ;

    public String getObjetivo() {
        return objetivo;
    }

    public String getNivel() {
        return nivel;
    }

    public Membresia getMembresia() {
        return Membresia;
    }

    public PlanEntrenamiento getPlanEntrenamiento() {
        return PlanEntrenamiento;
    }

    public Sesion get() {
        return ;
    }

    public void setObjetivo(String objetivo) {
        this.objetivo = objetivo;
    }

    public void setNivel(String nivel) {
        this.nivel = nivel;
    }

    public void setMembresia(Membresia Membresia) {
        this.Membresia = Membresia;
    }

    public void setPlanEntrenamiento(PlanEntrenamiento PlanEntrenamiento) {
        this.PlanEntrenamiento = PlanEntrenamiento;
    }

    public void set(Sesion ) {
        this. = ;
    }

    public void linkMembresia(Membresia _Membresia) {
        if (_Membresia != null) {
            _Membresia.getCliente().add(this);
        }

        unlinkMembresia();
        setMembresia(_Membresia);
    }

    public void linkPlanEntrenamiento(PlanEntrenamiento _PlanEntrenamiento) {
        if (_PlanEntrenamiento != null) {
            _PlanEntrenamiento.unlinkCliente();
            _PlanEntrenamiento.setCliente(this);
        }

        unlinkPlanEntrenamiento();
        setPlanEntrenamiento(_PlanEntrenamiento);
    }

    public void link(Sesion _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlinkMembresia() {
        if (getMembresia() != null) {
            getMembresia().getCliente().remove(this);
            setMembresia(null);
        }
    }

    public void unlinkPlanEntrenamiento() {
        if (getPlanEntrenamiento() != null) {
            getPlanEntrenamiento().setCliente(null);
            setPlanEntrenamiento(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAGXU7ld5F0X1wM= >>
    // ----------- >>
    public void verRutina() {
    // ----------- << method.body@AAAAAAGXU7ld5F0X1wM= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGXU7lvUF/BBLU= >>
    // ----------- >>
    public void reservarCita() {
    // ----------- << method.body@AAAAAAGXU7lvUF/BBLU= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGXU0vS8aN9XoE= >>
// ----------- >>
}