/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Dominio.Usuarios;

import java.util.*;
import java.time.*;


import domain.Usuario;
import persistence.Usuario;
// ----------- << imports@AAAAAAGXU0yWuaOIXTs= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXU0yWuaOIXTs= >>
// ----------- >>
public class CuentaUsuario {
    // ----------- << attribute.annotations@AAAAAAGXU7eXJ2hqFKw= >>
    // ----------- >>
    private String username;

    // ----------- << attribute.annotations@AAAAAAGXU7eoKGsUI7g= >>
    // ----------- >>
    private String password;

    // ----------- << attribute.annotations@AAAAAAGXU7e3tm5G2VA= >>
    // ----------- >>
    private String estado;

    // ----------- << attribute.annotations@AAAAAAGXU1H0rLGDBe4= >>
    // ----------- >>
    private Usuario Usuario;

    // ----------- << attribute.annotations@AAAAAAGXej9BzaW7SmY= >>
    // ----------- >>
    private Usuario ;

    // ----------- << attribute.annotations@AAAAAAGXej9BzqYanRA= >>
    // ----------- >>
    private Usuario ;

    public String getUsername() {
        return username;
    }

    public String getPassword() {
        return password;
    }

    public String getEstado() {
        return estado;
    }

    public Usuario getUsuario() {
        return Usuario;
    }

    public Usuario get() {
        return ;
    }

    public Usuario get() {
        return ;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public void setUsuario(Usuario Usuario) {
        this.Usuario = Usuario;
    }

    public void set(Usuario ) {
        this. = ;
    }

    public void set(Usuario ) {
        this. = ;
    }

    public void linkUsuario(Usuario _Usuario) {
        if (_Usuario != null) {
            _Usuario.unlinkCuentaUsuario();
            _Usuario.setCuentaUsuario(this);
        }

        unlinkUsuario();
        setUsuario(_Usuario);
    }

    public void link(Usuario _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Usuario _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlinkUsuario() {
        if (getUsuario() != null) {
            getUsuario().setCuentaUsuario(null);
            setUsuario(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAGXU7ocX20TMvM= >>
    // ----------- >>
    public void cambiarPassword() {
    // ----------- << method.body@AAAAAAGXU7ocX20TMvM= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGXU7orfm+9Dv0= >>
    // ----------- >>
    public void bloquearCuenta() {
    // ----------- << method.body@AAAAAAGXU7orfm+9Dv0= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGXU0yWuaOIXTs= >>
// ----------- >>
}