/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Dominio.Usuarios;

import java.util.*;
import java.time.*;


import Dominio.Rutinas.Rutina;
import Dominio.Sesiones.Sesion;
// ----------- << imports@AAAAAAGXU0x0AKOCYkQ= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXU0x0AKOCYkQ= >>
// ----------- >>
public class Entrenador extends Usuario {
    // ----------- << attribute.annotations@AAAAAAGXU7gdSKBzziA= >>
    // ----------- >>
    private String especialidad;

    // ----------- << attribute.annotations@AAAAAAGXU7g4eaMd5Qw= >>
    // ----------- >>
    private String certificaciones;

    // ----------- << attribute.annotations@AAAAAAGXU6iXFcCzSWQ= >>
    // ----------- >>
    private Rutina Rutina;

    // ----------- << attribute.annotations@AAAAAAGXU659jfzNFpM= >>
    // ----------- >>
    private Sesion Sesion;

    // ----------- << attribute.annotations@AAAAAAGXeog1297wCjM= >>
    // ----------- >>
    private Rutina Rutina;

    public String getEspecialidad() {
        return especialidad;
    }

    public String getCertificaciones() {
        return certificaciones;
    }

    public Rutina getRutina() {
        return Rutina;
    }

    public Sesion getSesion() {
        return Sesion;
    }

    public Rutina getRutina() {
        return Rutina;
    }

    public void setEspecialidad(String especialidad) {
        this.especialidad = especialidad;
    }

    public void setCertificaciones(String certificaciones) {
        this.certificaciones = certificaciones;
    }

    public void setRutina(Rutina Rutina) {
        this.Rutina = Rutina;
    }

    public void setSesion(Sesion Sesion) {
        this.Sesion = Sesion;
    }

    public void setRutina(Rutina Rutina) {
        this.Rutina = Rutina;
    }

    public void linkRutina(Rutina _Rutina) {
        if (_Rutina != null) {
            _Rutina.unlinkEntrenador();
            _Rutina.setEntrenador(this);
        }

        unlinkRutina();
        setRutina(_Rutina);
    }

    public void linkSesion(Sesion _Sesion) {
        if (_Sesion != null) {
            _Sesion.unlinkEntrenador();
            _Sesion.setEntrenador(this);
        }

        unlinkSesion();
        setSesion(_Sesion);
    }

    public void linkRutina(Rutina _Rutina) {
        if (_Rutina != null) {
            _Rutina.unlinkEntrenador();
            _Rutina.setEntrenador(this);
        }

        unlinkRutina();
        setRutina(_Rutina);
    }

    public void unlinkRutina() {
        if (getRutina() != null) {
            getRutina().setEntrenador(null);
            setRutina(null);
        }
    }

    public void unlinkSesion() {
        if (getSesion() != null) {
            getSesion().setEntrenador(null);
            setSesion(null);
        }
    }

    public void unlinkRutina() {
        if (getRutina() != null) {
            getRutina().setEntrenador(null);
            setRutina(null);
        }
    }

    // ----------- << method.annotations@AAAAAAGXU7mcQ2KYqx8= >>
    // ----------- >>
    public void crearRutina() {
    // ----------- << method.body@AAAAAAGXU7mcQ2KYqx8= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGXU7m19GUVUgQ= >>
    // ----------- >>
    public void verClientes() {
    // ----------- << method.body@AAAAAAGXU7m19GUVUgQ= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGXU0x0AKOCYkQ= >>
// ----------- >>
}