/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Dominio.Usuarios;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGXfDvvGnwPYXQ= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXfDvvGnwPYXQ= >>
// ----------- >>
public interface IUsuarioRepositorio {
    /**
    * @param Usuario usuario
    */

    // ----------- << method.annotations@AAAAAAGXfD1KmMda8Jk= >>
    // ----------- >>
    void guardar(void Usuario usuario);
    /**
    * @param Usuario usuario
    */

    // ----------- << method.annotations@AAAAAAGXfD1py8xDeC8= >>
    // ----------- >>
    void actualizar(void Usuario usuario);
    /**
    * @param String id
    */

    // ----------- << method.annotations@AAAAAAGXfD2lE9Esysg= >>
    // ----------- >>
    void eliminarPorId(void String id);
    /**
    * @param String id
    */

    // ----------- << method.annotations@AAAAAAGXfD274dZ1hWc= >>
    // ----------- >>
    void buscarPorId(void String id);
    // ----------- << method.annotations@AAAAAAGXfEIrgfBeogo= >>
    // ----------- >>
    void listarTodos();
// ----------- << interface.extras@AAAAAAGXfDvvGnwPYXQ= >>
// ----------- >>
}