/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Dominio.Usuarios;

import java.util.*;
import java.time.*;

import com.fasterxml.jackson.annotation.*;

import Dominio.Notificaciones.Notificacion;
// ----------- << imports@AAAAAAGXU0uiUKN6cNs= >>
// ----------- >>

@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        property = "type"
)
@JsonSubTypes({
        @JsonSubTypes.Type(value = Cliente.class, name = "cliente"),
        @JsonSubTypes.Type(value = Administrador.class, name = "administrador"),
        @JsonSubTypes.Type(value = Entrenador.class, name = "entrenador")
})
// ----------- << class.annotations@AAAAAAGXU0uiUKN6cNs= >>
// ----------- >>
public class Usuario {
    // ----------- << attribute.annotations@AAAAAAGXU5VpEPMMGpg= >>
    // ----------- >>
    private int id;

    // ----------- << attribute.annotations@AAAAAAGXU5YiV/Nc+x0= >>
    // ----------- >>
    private String nombre;

    // ----------- << attribute.annotations@AAAAAAGXU5Z50fOc+Os= >>
    // ----------- >>
    private String DNI;

    // ----------- << attribute.annotations@AAAAAAGXU7dLt18xRFs= >>
    // ----------- >>
    private String email;

    // ----------- << attribute.annotations@AAAAAAGXU7dcX2JiRoU= >>
    // ----------- >>
    private String telefono;

    // ----------- << attribute.annotations@AAAAAAGXU7duJWU5y2k= >>
    // ----------- >>
    private Date fechaNacimiento;

    // ----------- << attribute.annotations@AAAAAAGXU1H0rLGE2AU= >>
    // ----------- >>
    private CuentaUsuario CuentaUsuario;

    // ----------- << attribute.annotations@AAAAAAGXU7TZsy9W2eE= >>
    // ----------- >>
    private Notificacion Notificacion;

    public int getId() {
        return id;
    }

    public String getNombre() {
        return nombre;
    }

    public String getDNI() {
        return DNI;
    }

    public String getEmail() {
        return email;
    }

    public String getTelefono() {
        return telefono;
    }

    public Date getFechaNacimiento() {
        return fechaNacimiento;
    }

    public CuentaUsuario getCuentaUsuario() {
        return CuentaUsuario;
    }

    public Notificacion getNotificacion() {
        return Notificacion;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public void setDNI(String DNI) {
        this.DNI = DNI;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    public void setCuentaUsuario(CuentaUsuario CuentaUsuario) {
        this.CuentaUsuario = CuentaUsuario;
    }

    public void setNotificacion(Notificacion Notificacion) {
        this.Notificacion = Notificacion;
    }

    public void linkCuentaUsuario(CuentaUsuario _CuentaUsuario) {
        if (_CuentaUsuario != null) {
            _CuentaUsuario.unlinkUsuario();
            _CuentaUsuario.setUsuario(this);
        }

        unlinkCuentaUsuario();
        setCuentaUsuario(_CuentaUsuario);
    }

    public void linkNotificacion(Notificacion _Notificacion) {
        if (_Notificacion != null) {
            _Notificacion.unlinkUsuario();
            _Notificacion.setUsuario(this);
        }

        unlinkNotificacion();
        setNotificacion(_Notificacion);
    }

    public void unlinkCuentaUsuario() {
        if (getCuentaUsuario() != null) {
            getCuentaUsuario().setUsuario(null);
            setCuentaUsuario(null);
        }
    }

    public void unlinkNotificacion() {
        if (getNotificacion() != null) {
            getNotificacion().setUsuario(null);
            setNotificacion(null);
        }
    }

    // ----------- << method.annotations@AAAAAAGXU7jwFEBe/u4= >>
    // ----------- >>
    public void iniciarSesion() {
    // ----------- << method.body@AAAAAAGXU7jwFEBe/u4= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGXU7kZX0M1TKE= >>
    // ----------- >>
    public void cerrarSesion() {
    // ----------- << method.body@AAAAAAGXU7kZX0M1TKE= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGXU0uiUKN6cNs= >>
// ----------- >>
}