/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Dominio.Rutinas;

import java.util.*;
import java.time.*;


import application.Rutina;
import domain.Rutina;
import persistence.Rutina;
// ----------- << imports@AAAAAAGXU6RToGSDNd0= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXU6RToGSDNd0= >>
// ----------- >>
public class Ejercicio {
    // ----------- << attribute.annotations@AAAAAAGXU6YXYmzTXVs= >>
    // ----------- >>
    private String nombre;

    // ----------- << attribute.annotations@AAAAAAGXU6Yz5G2dKb8= >>
    // ----------- >>
    private String descripcion;

    // ----------- << attribute.annotations@AAAAAAGXU6ZLj26FMvQ= >>
    // ----------- >>
    private int repeticiones;

    // ----------- << attribute.annotations@AAAAAAGXU6ZgH29tPl4= >>
    // ----------- >>
    private int series;

    // ----------- << attribute.annotations@AAAAAAGXU6f78n5g3Gw= >>
    // ----------- >>
    private Rutina Rutina;

    // ----------- << attribute.annotations@AAAAAAGXej9BzaXyEtE= >>
    // ----------- >>
    private Rutina ;

    // ----------- << attribute.annotations@AAAAAAGXej9BzqZGGWY= >>
    // ----------- >>
    private Rutina ;

    // ----------- << attribute.annotations@AAAAAAGXej9BzqZp4lU= >>
    // ----------- >>
    private Rutina ;

    public String getNombre() {
        return nombre;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public int getRepeticiones() {
        return repeticiones;
    }

    public int getSeries() {
        return series;
    }

    public Rutina getRutina() {
        return Rutina;
    }

    public Rutina get() {
        return ;
    }

    public Rutina get() {
        return ;
    }

    public Rutina get() {
        return ;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public void setRepeticiones(int repeticiones) {
        this.repeticiones = repeticiones;
    }

    public void setSeries(int series) {
        this.series = series;
    }

    public void setRutina(Rutina Rutina) {
        this.Rutina = Rutina;
    }

    public void set(Rutina ) {
        this. = ;
    }

    public void set(Rutina ) {
        this. = ;
    }

    public void set(Rutina ) {
        this. = ;
    }

    public void linkRutina(Rutina _Rutina) {
        if (_Rutina != null) {
            _Rutina.unlinkEjercicio();
            _Rutina.setEjercicio(this);
        }

        unlinkRutina();
        setRutina(_Rutina);
    }

    public void link(Rutina _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Rutina _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Rutina _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlinkRutina() {
        if (getRutina() != null) {
            getRutina().setEjercicio(null);
            setRutina(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    /**
    * @param duracion
    */

    // ----------- << method.annotations@AAAAAAGXU7wfG9JYlsI= >>
    // ----------- >>
    public float calcularCaloriasQuemadas(int duracion) {
    // ----------- << method.body@AAAAAAGXU7wfG9JYlsI= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGXU6RToGSDNd0= >>
// ----------- >>
}