/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Dominio.Rutinas;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGXfEC1ocPuYMA= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXfEC1ocPuYMA= >>
// ----------- >>
public interface IRutinaRepositorio {
    /**
    * @param Rutina rutina
    */

    // ----------- << method.annotations@AAAAAAGXfEE5U9SbAuQ= >>
    // ----------- >>
    void guardar(void Rutina rutina);
    /**
    * @param Rutina rutina
    */

    // ----------- << method.annotations@AAAAAAGXfEE+xNbkIAw= >>
    // ----------- >>
    void actualizar(void Rutina rutina);
    /**
    * @param String id
    */

    // ----------- << method.annotations@AAAAAAGXfEFcR9kt/ns= >>
    // ----------- >>
    void eliminarPorId(void String id);
    /**
    * @param String id
    */

    // ----------- << method.annotations@AAAAAAGXfEFu8dt2C9Q= >>
    // ----------- >>
    void buscarPorId(void String id);
    // ----------- << method.annotations@AAAAAAGXfEG5Jd2/erE= >>
    // ----------- >>
    void listarTodas();
// ----------- << interface.extras@AAAAAAGXfEC1ocPuYMA= >>
// ----------- >>
}