/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Dominio.Rutinas;

import java.util.*;
import java.time.*;


import Dominio.Usuarios.Cliente;
import Usuarios.Cliente;
import domain.Cliente;
import domain.Usuarios.Cliente;
// ----------- << imports@AAAAAAGXU6Ra4GSkDyU= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXU6Ra4GSkDyU= >>
// ----------- >>
public class PlanEntrenamiento {
    // ----------- << attribute.annotations@AAAAAAGXU6aCAnNiUh0= >>
    // ----------- >>
    private int id;

    // ----------- << attribute.annotations@AAAAAAGXU6aVP3SlDsQ= >>
    // ----------- >>
    private Date fechaInicio;

    // ----------- << attribute.annotations@AAAAAAGXU6ao1XWNP4k= >>
    // ----------- >>
    private int duracionSemanas;

    // ----------- << attribute.annotations@AAAAAAGXU6huE6Ym1ME= >>
    // ----------- >>
    private Cliente cliente;

    // ----------- << attribute.annotations@AAAAAAGXU6gvZ4vyLR4= >>
    // ----------- >>
    private Rutina Rutina;

    // ----------- << attribute.annotations@AAAAAAGXej9BzaXNLzk= >>
    // ----------- >>
    private Cliente ;

    // ----------- << attribute.annotations@AAAAAAGXey7DgrMADqI= >>
    // ----------- >>
    private Cliente ;

    // ----------- << attribute.annotations@AAAAAAGXeoVZIVurAss= >>
    // ----------- >>
    private Cliente ;

    public int getId() {
        return id;
    }

    public Date getFechaInicio() {
        return fechaInicio;
    }

    public int getDuracionSemanas() {
        return duracionSemanas;
    }

    public Cliente getCliente() {
        return cliente;
    }

    public Rutina getRutina() {
        return Rutina;
    }

    public Cliente get() {
        return ;
    }

    public Cliente get() {
        return ;
    }

    public Cliente get() {
        return ;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    public void setDuracionSemanas(int duracionSemanas) {
        this.duracionSemanas = duracionSemanas;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public void setRutina(Rutina Rutina) {
        this.Rutina = Rutina;
    }

    public void set(Cliente ) {
        this. = ;
    }

    public void set(Cliente ) {
        this. = ;
    }

    public void set(Cliente ) {
        this. = ;
    }

    public void linkCliente(Cliente _cliente) {
        if (_cliente != null) {
            _cliente.unlinkPlanEntrenamiento();
            _cliente.setPlanEntrenamiento(this);
        }

        unlinkCliente();
        setCliente(_cliente);
    }

    public void linkRutina(Rutina _Rutina) {
        if (_Rutina != null) {
            _Rutina.unlinkPlanEntrenamiento();
            _Rutina.setPlanEntrenamiento(this);
        }

        unlinkRutina();
        setRutina(_Rutina);
    }

    public void link(Cliente _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Cliente _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Cliente _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlinkCliente() {
        if (getCliente() != null) {
            getCliente().setPlanEntrenamiento(null);
            setCliente(null);
        }
    }

    public void unlinkRutina() {
        if (getRutina() != null) {
            getRutina().setPlanEntrenamiento(null);
            setRutina(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    /**
    * @param Rutina
    */

    // ----------- << method.annotations@AAAAAAGXU7w3T9WNV8U= >>
    // ----------- >>
    public void asignarRutina(void Rutina) {
    // ----------- << method.body@AAAAAAGXU7w3T9WNV8U= >>
    // ----------- >>
    }
    /**
    * @param Rutina
    */

    // ----------- << method.annotations@AAAAAAGXU7xM3dhmpzU= >>
    // ----------- >>
    public void modificarRutina(void Rutina) {
    // ----------- << method.body@AAAAAAGXU7xM3dhmpzU= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGXU6Ra4GSkDyU= >>
// ----------- >>
}