/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Dominio.Rutinas;

import java.util.*;
import java.time.*;


import Dominio.Usuarios.Entrenador;
import Usuarios.Entrenador;
import domain.Entrenador;
import domain.Usuarios.Entrenador;
// ----------- << imports@AAAAAAGXU6PwLWRiu0U= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXU6PwLWRiu0U= >>
// ----------- >>
public class Rutina {
    // ----------- << attribute.annotations@AAAAAAGXU6V+/Gobdfc= >>
    // ----------- >>
    private int id;

    // ----------- << attribute.annotations@AAAAAAGXU6WTTmrWQx0= >>
    // ----------- >>
    private String nombre;

    // ----------- << attribute.annotations@AAAAAAGXU6WlSmvrBe8= >>
    // ----------- >>
    private String objetivo;

    // ----------- << attribute.annotations@AAAAAAGXU6iXFcCyK0M= >>
    // ----------- >>
    private Entrenador Entrenador;

    // ----------- << attribute.annotations@AAAAAAGXU6gvZ4vx1xQ= >>
    // ----------- >>
    private PlanEntrenamiento PlanEntrenamiento;

    // ----------- << attribute.annotations@AAAAAAGXU6f78n5h/bE= >>
    // ----------- >>
    private Ejercicio Ejercicio;

    // ----------- << attribute.annotations@AAAAAAGXeog1297xGes= >>
    // ----------- >>
    private Entrenador Entrenador;

    // ----------- << attribute.annotations@AAAAAAGXej9BzaXYvSo= >>
    // ----------- >>
    private Entrenador ;

    // ----------- << attribute.annotations@AAAAAAGXey7DgrMRKHk= >>
    // ----------- >>
    private Entrenador ;

    // ----------- << attribute.annotations@AAAAAAGXeoVZIVu3IyM= >>
    // ----------- >>
    private Entrenador ;

    public int getId() {
        return id;
    }

    public String getNombre() {
        return nombre;
    }

    public String getObjetivo() {
        return objetivo;
    }

    public Entrenador getEntrenador() {
        return Entrenador;
    }

    public PlanEntrenamiento getPlanEntrenamiento() {
        return PlanEntrenamiento;
    }

    public Ejercicio getEjercicio() {
        return Ejercicio;
    }

    public Entrenador getEntrenador() {
        return Entrenador;
    }

    public Entrenador get() {
        return ;
    }

    public Entrenador get() {
        return ;
    }

    public Entrenador get() {
        return ;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public void setObjetivo(String objetivo) {
        this.objetivo = objetivo;
    }

    public void setEntrenador(Entrenador Entrenador) {
        this.Entrenador = Entrenador;
    }

    public void setPlanEntrenamiento(PlanEntrenamiento PlanEntrenamiento) {
        this.PlanEntrenamiento = PlanEntrenamiento;
    }

    public void setEjercicio(Ejercicio Ejercicio) {
        this.Ejercicio = Ejercicio;
    }

    public void setEntrenador(Entrenador Entrenador) {
        this.Entrenador = Entrenador;
    }

    public void set(Entrenador ) {
        this. = ;
    }

    public void set(Entrenador ) {
        this. = ;
    }

    public void set(Entrenador ) {
        this. = ;
    }

    public void linkEntrenador(Entrenador _Entrenador) {
        if (_Entrenador != null) {
            _Entrenador.unlinkRutina();
            _Entrenador.setRutina(this);
        }

        unlinkEntrenador();
        setEntrenador(_Entrenador);
    }

    public void linkPlanEntrenamiento(PlanEntrenamiento _PlanEntrenamiento) {
        if (_PlanEntrenamiento != null) {
            _PlanEntrenamiento.unlinkRutina();
            _PlanEntrenamiento.setRutina(this);
        }

        unlinkPlanEntrenamiento();
        setPlanEntrenamiento(_PlanEntrenamiento);
    }

    public void linkEjercicio(Ejercicio _Ejercicio) {
        if (_Ejercicio != null) {
            _Ejercicio.unlinkRutina();
            _Ejercicio.setRutina(this);
        }

        unlinkEjercicio();
        setEjercicio(_Ejercicio);
    }

    public void linkEntrenador(Entrenador _Entrenador) {
        if (_Entrenador != null) {
            _Entrenador.unlinkRutina();
            _Entrenador.setRutina(this);
        }

        unlinkEntrenador();
        setEntrenador(_Entrenador);
    }

    public void link(Entrenador _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Entrenador _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Entrenador _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlinkEntrenador() {
        if (getEntrenador() != null) {
            getEntrenador().setRutina(null);
            setEntrenador(null);
        }
    }

    public void unlinkPlanEntrenamiento() {
        if (getPlanEntrenamiento() != null) {
            getPlanEntrenamiento().setRutina(null);
            setPlanEntrenamiento(null);
        }
    }

    public void unlinkEjercicio() {
        if (getEjercicio() != null) {
            getEjercicio().setRutina(null);
            setEjercicio(null);
        }
    }

    public void unlinkEntrenador() {
        if (getEntrenador() != null) {
            getEntrenador().setRutina(null);
            setEntrenador(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    /**
    * @param Ejercicio
    */

    // ----------- << method.annotations@AAAAAAGXU7vXbMSINlw= >>
    // ----------- >>
    public void agregarEjercicio(void Ejercicio) {
    // ----------- << method.body@AAAAAAGXU7vXbMSINlw= >>
    // ----------- >>
    }
    /**
    * @param Ejercicio
    */

    // ----------- << method.annotations@AAAAAAGXU7vsRsdhX6o= >>
    // ----------- >>
    public void quitarEjercicio(void Ejercicio) {
    // ----------- << method.body@AAAAAAGXU7vsRsdhX6o= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGXU7wAhs+uK6M= >>
    // ----------- >>
    public void mostrarRutina() {
    // ----------- << method.body@AAAAAAGXU7wAhs+uK6M= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGXU6PwLWRiu0U= >>
// ----------- >>
}