/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Dominio.Membresías;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGXfD6aDRFlRRI= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXfD6aDRFlRRI= >>
// ----------- >>
public interface IMembresiaRepositorio {
    /**
    * @param Membresia membresia
    */

    // ----------- << method.annotations@AAAAAAGXfD8cBC7UTfw= >>
    // ----------- >>
    void guardar(void Membresia membresia);
    /**
    * @param Membresia membresia
    */

    // ----------- << method.annotations@AAAAAAGXfD+6a4bdaqw= >>
    // ----------- >>
    void actualizar(void Membresia membresia);
    /**
    * @param String id
    */

    // ----------- << method.annotations@AAAAAAGXfD/VmovGtzE= >>
    // ----------- >>
    void eliminarPorId(void String id);
    /**
    * @param String id
    */

    // ----------- << method.annotations@AAAAAAGXfD/qXo+/KtQ= >>
    // ----------- >>
    void buscarPorId(void String id);
    // ----------- << method.annotations@AAAAAAGXfEIHVelmf98= >>
    // ----------- >>
    void listarTodas();
// ----------- << interface.extras@AAAAAAGXfD6aDRFlRRI= >>
// ----------- >>
}