/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Dominio.Membresías;

import java.util.*;
import java.time.*;


import Dominio.Usuarios.Cliente;
import Usuarios.Cliente;
import domain.Cliente;
import domain.Usuarios.Cliente;
// ----------- << imports@AAAAAAGXU5o21PZbk8I= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXU5o21PZbk8I= >>
// ----------- >>
public class Membresia {
    // ----------- << attribute.annotations@AAAAAAGXU5uLIP2x0Qk= >>
    // ----------- >>
    private String idMembresia;

    // ----------- << attribute.annotations@AAAAAAGXU5uzS/3ojIQ= >>
    // ----------- >>
    private Date fechaInicio;

    // ----------- << attribute.annotations@AAAAAAGXU5vUFP4TYM8= >>
    // ----------- >>
    private Date fechaFin;

    // ----------- << attribute.annotations@AAAAAAGXU5vpAf5HfD4= >>
    // ----------- >>
    private String estado;

    // ----------- << attribute.annotations@AAAAAAGXU53byAavESM= >>
    // ----------- >>
    private Set<Cliente> cliente = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAGXU58ttg3AeH0= >>
    // ----------- >>
    private Set<PagoMembresia> PagoMembresia = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAGXU6KYJl2aqQo= >>
    // ----------- >>
    private TipoMembresia tipomenbresia;

    // ----------- << attribute.annotations@AAAAAAGXej9BzaXKX/s= >>
    // ----------- >>
    private Set<Cliente>  = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAGXey7DgrL9Z+4= >>
    // ----------- >>
    private Set<Cliente>  = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAGXeoVZIVuoMPc= >>
    // ----------- >>
    private Set<Cliente>  = new HashSet<>();

    public String getIdMembresia() {
        return idMembresia;
    }

    public Date getFechaInicio() {
        return fechaInicio;
    }

    public Date getFechaFin() {
        return fechaFin;
    }

    public String getEstado() {
        return estado;
    }

    public Set<Cliente> getCliente() {
        return cliente;
    }

    public Set<PagoMembresia> getPagoMembresia() {
        return PagoMembresia;
    }

    public TipoMembresia getTipomenbresia() {
        return tipomenbresia;
    }

    public Set<Cliente> get() {
        return ;
    }

    public Set<Cliente> get() {
        return ;
    }

    public Set<Cliente> get() {
        return ;
    }

    public void setIdMembresia(String idMembresia) {
        this.idMembresia = idMembresia;
    }

    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public void setTipomenbresia(TipoMembresia tipomenbresia) {
        this.tipomenbresia = tipomenbresia;
    }

    public void linkCliente(Cliente _cliente) {
        if (_cliente != null) {
            _cliente.unlinkMembresia();
            _cliente.setMembresia(this);
            getCliente().add(_cliente);
        }
    }

    public void linkPagoMembresia(PagoMembresia _PagoMembresia) {
        if (_PagoMembresia != null) {
            _PagoMembresia.unlinkMenbresia();
            _PagoMembresia.setMenbresia(this);
            getPagoMembresia().add(_PagoMembresia);
        }
    }

    public void linkTipomenbresia(TipoMembresia _tipomenbresia) {
        if (_tipomenbresia != null) {
            _tipomenbresia.unlinkMembresia();
            _tipomenbresia.setMembresia(this);
        }

        unlinkTipomenbresia();
        setTipomenbresia(_tipomenbresia);
    }

    public void link(Cliente _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
            get().add(_);
        }
    }

    public void link(Cliente _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
            get().add(_);
        }
    }

    public void link(Cliente _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
            get().add(_);
        }
    }

    public void unlinkCliente(Cliente _cliente) {
        if (_cliente != null) {
            _cliente.setMembresia(null);
            getCliente().remove(_cliente);
        }
    }

    public void unlinkCliente(Cliente _cliente, Iterator<Cliente> it) {
        if (_cliente != null) {
            _cliente.setMembresia(null);
            it.remove();
        }
    }

    public void unlinkPagoMembresia(PagoMembresia _PagoMembresia) {
        if (_PagoMembresia != null) {
            _PagoMembresia.setMenbresia(null);
            getPagoMembresia().remove(_PagoMembresia);
        }
    }

    public void unlinkPagoMembresia(PagoMembresia _PagoMembresia, Iterator<PagoMembresia> it) {
        if (_PagoMembresia != null) {
            _PagoMembresia.setMenbresia(null);
            it.remove();
        }
    }

    public void unlinkTipomenbresia() {
        if (getTipomenbresia() != null) {
            getTipomenbresia().setMembresia(null);
            setTipomenbresia(null);
        }
    }

    public void unlink(Cliente _) {
        if (_ != null) {
            _.set(null);
            get().remove(_);
        }
    }

    public void unlink(Cliente _, Iterator<Cliente> it) {
        if (_ != null) {
            _.set(null);
            it.remove();
        }
    }

    public void unlink(Cliente _) {
        if (_ != null) {
            _.set(null);
            get().remove(_);
        }
    }

    public void unlink(Cliente _, Iterator<Cliente> it) {
        if (_ != null) {
            _.set(null);
            it.remove();
        }
    }

    public void unlink(Cliente _) {
        if (_ != null) {
            _.set(null);
            get().remove(_);
        }
    }

    public void unlink(Cliente _, Iterator<Cliente> it) {
        if (_ != null) {
            _.set(null);
            it.remove();
        }
    }

    // ----------- << method.annotations@AAAAAAGXU7tFhJexXoQ= >>
    // ----------- >>
    public void activar() {
    // ----------- << method.body@AAAAAAGXU7tFhJexXoQ= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGXU7tYKZq1ZzM= >>
    // ----------- >>
    public void cancelar() {
    // ----------- << method.body@AAAAAAGXU7tYKZq1ZzM= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGXU7tpfp4URE8= >>
    // ----------- >>
    public boolean esActiva() {
    // ----------- << method.body@AAAAAAGXU7tpfp4URE8= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGXU5o21PZbk8I= >>
// ----------- >>
}