/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Dominio.Membresías;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGXU5rj6v1ybb4= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXU5rj6v1ybb4= >>
// ----------- >>
public class MetodoPago {
    // ----------- << attribute.annotations@AAAAAAGXU50bCwQROek= >>
    // ----------- >>
    private String tipo;

    // ----------- << attribute.annotations@AAAAAAGXU6ChfyVYdjY= >>
    // ----------- >>
    private PagoMembresia pagoMenbreswia;

    public String getTipo() {
        return tipo;
    }

    public PagoMembresia getPagoMenbreswia() {
        return pagoMenbreswia;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public void setPagoMenbreswia(PagoMembresia pagoMenbreswia) {
        this.pagoMenbreswia = pagoMenbreswia;
    }

    public void linkPagoMenbreswia(PagoMembresia _pagoMenbreswia) {
        if (_pagoMenbreswia != null) {
            _pagoMenbreswia.unlinkMetodoPago();
            _pagoMenbreswia.setMetodoPago(this);
        }

        unlinkPagoMenbreswia();
        setPagoMenbreswia(_pagoMenbreswia);
    }

    public void unlinkPagoMenbreswia() {
        if (getPagoMenbreswia() != null) {
            getPagoMenbreswia().setMetodoPago(null);
            setPagoMenbreswia(null);
        }
    }

    // ----------- << method.annotations@AAAAAAGXU7un0q8MJlM= >>
    // ----------- >>
    public void validarMetodo() {
    // ----------- << method.body@AAAAAAGXU7un0q8MJlM= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGXU5rj6v1ybb4= >>
// ----------- >>
}