/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Dominio.Membresías;

import java.util.*;
import java.time.*;


import application.Membresia;
import domain.Membresia;
import persistence.Membresia;
// ----------- << imports@AAAAAAGXU5rQpP1jjv4= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXU5rQpP1jjv4= >>
// ----------- >>
public class PagoMembresia {
    // ----------- << attribute.annotations@AAAAAAGXU5ys8wLJkAs= >>
    // ----------- >>
    private String idPago;

    // ----------- << attribute.annotations@AAAAAAGXU5zA6ALxIP4= >>
    // ----------- >>
    private float monto;

    // ----------- << attribute.annotations@AAAAAAGXU5zT8AMlnzY= >>
    // ----------- >>
    private Date fechaPago;

    // ----------- << attribute.annotations@AAAAAAGXU58ttg2/wwQ= >>
    // ----------- >>
    private Membresia Menbresia;

    // ----------- << attribute.annotations@AAAAAAGXU6ChfyVZF7Q= >>
    // ----------- >>
    private MetodoPago MetodoPago;

    // ----------- << attribute.annotations@AAAAAAGXej9BzaXjlMw= >>
    // ----------- >>
    private Membresia ;

    // ----------- << attribute.annotations@AAAAAAGXej9BzqYpaNY= >>
    // ----------- >>
    private Membresia ;

    // ----------- << attribute.annotations@AAAAAAGXej9BzqZaGrI= >>
    // ----------- >>
    private Membresia ;

    public String getIdPago() {
        return idPago;
    }

    public float getMonto() {
        return monto;
    }

    public Date getFechaPago() {
        return fechaPago;
    }

    public Membresia getMenbresia() {
        return Menbresia;
    }

    public MetodoPago getMetodoPago() {
        return MetodoPago;
    }

    public Membresia get() {
        return ;
    }

    public Membresia get() {
        return ;
    }

    public Membresia get() {
        return ;
    }

    public void setIdPago(String idPago) {
        this.idPago = idPago;
    }

    public void setMonto(float monto) {
        this.monto = monto;
    }

    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }

    public void setMenbresia(Membresia Menbresia) {
        this.Menbresia = Menbresia;
    }

    public void setMetodoPago(MetodoPago MetodoPago) {
        this.MetodoPago = MetodoPago;
    }

    public void set(Membresia ) {
        this. = ;
    }

    public void set(Membresia ) {
        this. = ;
    }

    public void set(Membresia ) {
        this. = ;
    }

    public void linkMenbresia(Membresia _Menbresia) {
        if (_Menbresia != null) {
            _Menbresia.getPagoMembresia().add(this);
        }

        unlinkMenbresia();
        setMenbresia(_Menbresia);
    }

    public void linkMetodoPago(MetodoPago _MetodoPago) {
        if (_MetodoPago != null) {
            _MetodoPago.unlinkPagoMenbreswia();
            _MetodoPago.setPagoMenbreswia(this);
        }

        unlinkMetodoPago();
        setMetodoPago(_MetodoPago);
    }

    public void link(Membresia _) {
        if (_ != null) {
            _.get().add(this);
        }

        unlink();
        set(_);
    }

    public void link(Membresia _) {
        if (_ != null) {
            _.get().add(this);
        }

        unlink();
        set(_);
    }

    public void link(Membresia _) {
        if (_ != null) {
            _.get().add(this);
        }

        unlink();
        set(_);
    }

    public void unlinkMenbresia() {
        if (getMenbresia() != null) {
            getMenbresia().getPagoMembresia().remove(this);
            setMenbresia(null);
        }
    }

    public void unlinkMetodoPago() {
        if (getMetodoPago() != null) {
            getMetodoPago().setPagoMenbreswia(null);
            setMetodoPago(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().get().remove(this);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().get().remove(this);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().get().remove(this);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAGXU7uCgqkEWTQ= >>
    // ----------- >>
    public void procesarPago() {
    // ----------- << method.body@AAAAAAGXU7uCgqkEWTQ= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGXU7uTsqvbZfc= >>
    // ----------- >>
    public void verificarPago() {
    // ----------- << method.body@AAAAAAGXU7uTsqvbZfc= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGXU5rQpP1jjv4= >>
// ----------- >>
}