/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Dominio.Membresías;

import java.util.*;
import java.time.*;


import application.Membresia;
import domain.Membresia;
import persistence.Membresia;
// ----------- << imports@AAAAAAGXU5q+nf1UFgE= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXU5q+nf1UFgE= >>
// ----------- >>
public class TipoMembresia {
    // ----------- << attribute.annotations@AAAAAAGXU5wmsP8n630= >>
    // ----------- >>
    private String nombre;

    // ----------- << attribute.annotations@AAAAAAGXU5xb2/+c3Z4= >>
    // ----------- >>
    private int duracionDias;

    // ----------- << attribute.annotations@AAAAAAGXU5xvpP/QkeI= >>
    // ----------- >>
    private float precio;

    // ----------- << attribute.annotations@AAAAAAGXU6KYJl2Z8Ek= >>
    // ----------- >>
    private Membresia membresia;

    // ----------- << attribute.annotations@AAAAAAGXej9BzaXmUPc= >>
    // ----------- >>
    private Membresia ;

    // ----------- << attribute.annotations@AAAAAAGXej9BzqYsBoM= >>
    // ----------- >>
    private Membresia ;

    // ----------- << attribute.annotations@AAAAAAGXej9BzqZdGSY= >>
    // ----------- >>
    private Membresia ;

    public String getNombre() {
        return nombre;
    }

    public int getDuracionDias() {
        return duracionDias;
    }

    public float getPrecio() {
        return precio;
    }

    public Membresia getMembresia() {
        return membresia;
    }

    public Membresia get() {
        return ;
    }

    public Membresia get() {
        return ;
    }

    public Membresia get() {
        return ;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public void setDuracionDias(int duracionDias) {
        this.duracionDias = duracionDias;
    }

    public void setPrecio(float precio) {
        this.precio = precio;
    }

    public void setMembresia(Membresia membresia) {
        this.membresia = membresia;
    }

    public void set(Membresia ) {
        this. = ;
    }

    public void set(Membresia ) {
        this. = ;
    }

    public void set(Membresia ) {
        this. = ;
    }

    public void linkMembresia(Membresia _membresia) {
        if (_membresia != null) {
            _membresia.unlinkTipomenbresia();
            _membresia.setTipomenbresia(this);
        }

        unlinkMembresia();
        setMembresia(_membresia);
    }

    public void link(Membresia _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Membresia _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Membresia _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlinkMembresia() {
        if (getMembresia() != null) {
            getMembresia().setTipomenbresia(null);
            setMembresia(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

// ----------- << class.extras@AAAAAAGXU5q+nf1UFgE= >>
// ----------- >>
}