/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Servicios;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGXfCHQZyF/JO4= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXfCHQZyF/JO4= >>
// ----------- >>
public interface IMembresiaService {
// ----------- << interface.extras@AAAAAAGXfCHQZyF/JO4= >>
// ----------- >>
}