/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Servicios;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGXfCHkWiPF4Jo= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXfCHkWiPF4Jo= >>
// ----------- >>
public interface ISesionService {
// ----------- << interface.extras@AAAAAAGXfCHkWiPF4Jo= >>
// ----------- >>
}