/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Servicios;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGXfCkea3xdlWg= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXfCkea3xdlWg= >>
// ----------- >>
public class MembresiaServiceImpl implements IMembresiaService {
// ----------- << class.extras@AAAAAAGXfCkea3xdlWg= >>
// ----------- >>
}