/*
* This code has been generated by the Javazzar: a code generator for modern Java.
*
* Drop me a line or two at aleksandar.radulovic@gmail.com: I'd love to hear from you!
*/
package Servicios;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGXfCnciJs+7n0= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGXfCnciJs+7n0= >>
// ----------- >>
public class NotificacionServiceImpl implements INotificacionService {
// ----------- << class.extras@AAAAAAGXfCnciJs+7n0= >>
// ----------- >>
}